### ISSUE TITLE
Fatal error when running grunt sectv-build:sectv-tizen

### ISSUE THREAD

**Issue by AlexGustafsson** [Samsung/cordova-plugin-toast#30]
I'm encountering an error when trying to build for Tizen with TOAST.

- macOS 10.12.3-beta (16D17a)
- Tizen Studio v1.0.2
- Java 8 update 111 (build 1.8.0_111-b14)
- Fresh install of TOAST by following the wiki [here](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-to-start), [here](https://github.com/Samsung/cordova-plugin-toast/wiki/Create-Project) and [here](https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build) and using [the shell file](https://github.com/Samsung/cordova-plugin-toast/blob/master/script/shell/Getting_Started.sh).

```
$ grunt sectv-build:sectv-tizen
Running "sectv-build:sectv-tizen" (sectv-build) task

Start packaging Samsung Tizen TV Platform......
Tizen CLI 1.3.5

Setting configuration is succeeded....

Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path:/Users/username/Documents/Apps/Tizen/toast/TestApp/platforms/sectv-tizen/www/.buildResult
Excluded: [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.989
Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/core/gputil/XMLUtil
	at org.tizen.ncli.subcommands.packages.WebProject.getDocument(WebProject.java:41)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:118)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:74)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:85)
	at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:710)
	at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:858)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:82)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:145)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:77)
Caused by: java.lang.ClassNotFoundException: org.tizen.core.gputil.XMLUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Fatal error: Exception in thread "main" java.lang.NoClassDefFoundError: org/tizen/core/gputil/XMLUtil
	at org.tizen.ncli.subcommands.packages.WebProject.getDocument(WebProject.java:41)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:118)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:74)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:85)
	at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:710)
	at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:858)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:82)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:145)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:77)
Caused by: java.lang.ClassNotFoundException: org.tizen.core.gputil.XMLUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

**Comment by jamesmskelsey** [comment]
Having the exact same problem. What I had to was manually open Tizen, create a new empty project, copy the contents of .build-result in to the folder in the workspace created by tizen, and then package the application manually. Annoying, but the only way I was able to get anything work. Best of luck, and if you happen to get it to work without doing all of that, please let me know!

**Comment by yongjuYoon** [comment]
Hi,

Your error was occurred due to problem of the environment variable setup process.
(Related Link : https://github.com/Samsung/cordova-plugin-toast/wiki/Prepare-and-Build#how-to-build-and-package)

If you used 'tizen studio', plz check again.
C:\tizen-studio\tools\ide\bin (O) / C:\tizen-sdk\tools\ide\bin (X)

Thank you

**Comment by jamesmskelsey** [comment]
So, since I already had those set up, I looked at the Tizen Package Manager and installed... basically every CLI I could find. It got me past this error, but now is telling me that the "Path must be a string" because.... it looks like someone is passing in an Array of... the Package File Location, an index, an input with 'Author certficate' (typo is yours, that's how it's spelled)... but I get what appears to be a valid wgt out of the deal.

Because it turns out that my previously mentioned method doesn't work at all. Actually tried running my app in the "oh so wonderful emulator" that comes with Tizen Studio and for some reason cordova is deciding to load things I didn't ask for... like the $webapis from... apparently the wrong place. It complains about that. Then the Toast media player doesn't work. So... what I'll do is just go ahead and waste some poor QA guys time and submit whatever this spit out as an app and hope for the best. Because you know what? It worked in the emulator.

**Comment by bstegman** [comment]
I'm having the same issue (https://github.com/Samsung/cordova-plugin-toast/issues/32) when you submitted this to the store did they say it was invalid.  If not I'm going to go ahead and do the same thing.  I was building fine and then it stopped.

**Comment by yongjuYoon** [comment]
@AlexGustafsson 
The reason of "NoClassDefFoundError" error is the non-installation of "Native CLI"
Please check again.
Related url : http://developer.samsung.com/tv/develop/getting-started/using-sdk/cli

**Comment by yongjuYoon** [comment]
@jamesmskelsey @bstegman 
You can solve this problem([#32](https://github.com/Samsung/cordova-plugin-toast/issues/32)) now.
We fixed the code related this error that is not critical.

So plz update the "grunt-cordova-sectv" for using "git pull" now.
Related url : https://github.com/Samsung/grunt-cordova-sectv

And then if you build project, you will fine.

Thank you.

**Comment by joshuairl** [comment]
@yongjuYoon I just ran the shell script install and am getting this error still...

Is the answer the "Native CLI" stuff?

**Comment by joshuairl** [comment]
Yes, I just had to install Native CLI.  We good. :)

**Comment by joshuairl** [comment]
Don't you just love it when you get an error, google it... and then your face pops up on the github issue already... Anyway... installing Native CLI Hahaha
